# Generated by Django 4.0 on 2022-05-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Re_app', '0003_remove_profile_followers_remove_profile_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='auth.user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='auth.user'),
        ),
    ]
