# Generated by Django 4.0 on 2022-05-18 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Re_app', '0007_remove_profile_followers_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='userpost',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
